version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: mdillon/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-pass
      PGDATA: /data/postgres
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    ports:
      - "127.0.0.1:5432:5432" #external:internal
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: